name = "wai-chat-bot-react"
main = "src/worker/index.ts"
compatibility_date = "2022-05-03"
compatibility_flags = ["streams_enable_constructors"]
account_id=""

logpush = true
node_compat = true

[dev]
ip = "localhost"

[site]
bucket = "./build"

[[kv_namespaces]]
# binding 的值 需要跟 [vars] / KV_NAMESPACE_BINDING_KEY 一致
# 在 https://dash.cloudflare.com/ > Workers > KV : Create a namespace
binding = "WAI_KV_PROD"
id = ""
preview_id = ""

[vars]
KV_NAMESPACE_BINDING_KEY="WAI_KV_PROD"
Access_Control_Allow_Origin="*"
IS_PROD = true
